name: timbrer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch=1.9.0
  - torchvision=0.10.0
  - torchaudio=0.9.0
  - cudatoolkit=10.2
  - python-sounddevice
  - librosa<0.10 # deprecated syntax within torchlibrosa 0.0.9
  - tqdm
  - pip
  - pip:
    - pydub==0.25.1 # for mp3 I/O
    - torchlibrosa==0.0.9
    - nnAudio==0.3.1
    - sf2utils
    - mido
    - dominate

# conda env update -f environment.yml --prune

