name: timbrer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - librosa=0.6
  - pytorch=1.1
  - torchvision
  - cudatoolkit=10.0
  - python-sounddevice
  - tensorflow
  -pip:
	- sf2utils
	- mido
	- dominate
# conda env update -f environment.yml --prune

