name: timbrer
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.6
  - librosa=0.6
  - pytorch=1.1
  - torchvision
  - cudatoolkit=10.0
  - python-sounddevice
  - tensorflow=1.13
  - pip
  - pip:
    - sf2utils
    - mido
    - tensorflow-probability==0.6 # 0.6+ for lbfgs_minimize

# conda env update -f environment.yml --prune

